### PR TITLE
Update DG Tag implementations

### LINKED ISSUE #452: [Bryan] Update DG Implementation
Update DG Implementation for Tag Commands (with Eugene)

### PR DESCRIPTION
**Pull request by bryanljx**
Closes #452.

### Changes made:
- Fix error in previous sequence diagrams for Tag functions
- Add sequence and activity diagram for `filtertag`
- Update TagFeatures section

### CODE REVIEW

**Review by Eugenetanwl3881 — COMMENTED** [review]
1 nitpick: why does the last 2 boxes in your activity diagram start with : ?
Is it a typo?

**Review by RichDom2185 — DISMISSED** [review]
LGTM, thanks for the bug fixes!

**Review by Eugenetanwl3881 — APPROVED** [review]
Thanks for updating! LGTM

**Review by RichDom2185 — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
