### PR TITLE
Fix filtertag sequence diagram

### PR DESCRIPTION
**Pull request by bryanljx**
## Issue
Unnecessary arrow in sequence diagram:

image

## Changes made:
- Fix filtertag sequence diagram

### CODE REVIEW

**Comment by RichDom2185** [comment]
What's the diamond at the bottom of the PNGs?

**Comment by bryanljx** [comment]
> What's the diamond at the bottom of the PNGs?

That's the extra merge node that I am removing non this PR. It's used for alternate pathways like these if they join back later. 

For eg, the "if" and "else" branch joins back together after a while.

**Review by Eugenetanwl3881 — CHANGES_REQUESTED** [review]
The activity diagrams still have a diamond at the bottom

**Review by Eugenetanwl3881 — APPROVED** [review]
LGTM

**Pull request merged**
