### PR TITLE
Update "reset" command

### LINKED ISSUE #120: Update "reset" command
Originally "clear" in AB3

### PR DESCRIPTION
**Pull request by Eugenetanwl3881**
Closes #120

Refactored the AB3 clear command to FoodRem reset command (based on agreed-upon commands). 
Clears the items and tags in FoodRem.

Outstanding tasks:
- Testing (will be done later when create tag method has been implemented and merged)

### CODE REVIEW

**Comment by RichDom2185** [comment]
Is this a duplicate of #176? @yixiann

**Review by RichDom2185 — DISMISSED** [review]
LGTM

**Review by RichDom2185 — APPROVED** [review]
LGTM, thanks!

**Comment by Ferusel** [comment]
LGTM!

**Pull request merged**
